nome = input('Qual seu nome? ')
idade = input('Qual sua idade? ')
peso = input('Qual seu peso? ')
# print(nome, ',', idade, ' anos ,', peso, ' kgs')
print('{}, {} anos, {} kgs'.format(nome, idade, peso))
